name: Build Docker images

on:
  push:
    paths:
      - "services/**/Dockerfile"
      - "services/**"
      - "common/**"
  pull_request:
    paths:
      - "services/**/Dockerfile"
      - "services/**"
      - "common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [coordinator, scraper]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        run:
          docker login --username ${{vars.USERNAME}} --password ${{secrets.PAT}} ${{vars.REGISTRY}}



      - name: Build ${{ matrix.service }}
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          set -euxo pipefail
          SERVICE="${{ matrix.service }}"
          TAG="${SERVICE}:${GITHUB_SHA:-dev}"

          # Use repo root as build context so Dockerfiles can COPY common/ etc.
          docker build \
            -f "services/${SERVICE}/Dockerfile" \
            -t "${TAG}" \
            .

          docker image ls "${TAG}"


